### ISSUE TITLE
GD-2.50 Fails to build on fedora-21 x86_64 => GD-2.56 is OK.

### ISSUE THREAD

**Issue by olahaye74** [naemon/naemon-core#110]
replacing GD-2.50.tar.gz with GD-2.56.tar.gz in https://github.com/sni/thruk_libs/blob/master/Makefile fixes the build problem on fedora-21.

**Comment by sni** [comment]
as far as i remember, the latest GD module requires recent Module::Build which on the other hand fails on older fedora releases. Thats why i haven't updated this yet.

**Comment by olahaye74** [comment]
Ho :-( You're right, it even fails to build on rhel-7 :-(

Any intermediate version that would succeed in both situations?

Best regards.

--
   Olivier LAHAYE
   CEA DRT/LIST/DIR
________________________________
De : Sven Nierlein [notifications@github.com]
Envoyé : mardi 21 avril 2015 15:09
À : naemon/naemon-core
Cc : LAHAYE Olivier
Objet : Re: [naemon-core] GD-2.50 Fails to build on fedora-21 x86_64 => GD-2.56 is OK. (#110)


as far as i remember, the latest GD module requires recent Module::Build which on the other hand fails on older fedora releases. Thats why i haven't updated this yet.

**Comment by sni** [comment]
whats the actual problem? You only provided a solution :-)

**Comment by olahaye74** [comment]
Hi Sven,

If I set GD to v2.56 instead of V2.50, I'm able to build flawlesly naemon on fedora-21, but as you pointed out, it'll fail on distros with perl(Module::Build) < 0.42

And on Centos-7, as this build module is v0.40 only, build fails in the following way:
-----8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<----------
*** ( 36/218) GD-2.56.tar.gz                                         installing... error: error: rc 65280
Configuring for libgd version 2.0.34.
Checking for stray libgd header files...none found.

Included Features:          GD_XPM GD_JPEG GD_FONTCONFIG GD_FREETYPE GD_PNG GD_GIF GD_GIFANIM GD_OPENPOLYGON GD_UNCLOSEDPOLY GD_ANIMGIF GD_FTCIRCLE VERSION_33
GD library used from:       /usr
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'GD' version '2.56'
Module::Build version 0.42 required--this is only version 0.4005 at ./Build line 43.


make[2]: *** [build] Error 255
make[2]: Leaving directory `/root/rpmbuild/BUILD/naemon-1.0.3/thruk/libs'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/naemon-1.0.3/thruk'
make: *** [thruk] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.FN0V9B (%build)
-----8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<-----------8<----------

What is wired, is that it can be built on Centos-6 using GD-2.56!!!! Eventhough Module::Build is v0.35 it works. This is wired and I don't understand why.......

In fact, I wanted to build naemon for CentOS-6, CentOS-7 and fedora-21 (subpackage for OSCAR Cluster  which I'm currently working on updating its components.

So the question is mainly, is there a GD version beween 0.50 and 0.56 that would fit those 3 distros without breaking naemon build...

Best regards.
--
   Olivier LAHAYE
   CEA DRT/LIST/DIR
________________________________
De : Sven Nierlein [notifications@github.com]
Envoyé : mardi 21 avril 2015 16:39
À : naemon/naemon-core
Cc : LAHAYE Olivier
Objet : Re: [naemon-core] GD-2.50 Fails to build on fedora-21 x86_64 => GD-2.56 is OK. (#110)


whats the actual problem? You only provided a solution :-)

**Comment by sni** [comment]
You know that there are packages for Centos 6 and Centos 7 already? They work perfectly with GD-2.50.
And you still didn't post any details about the inital error.

**Comment by catharsis** [comment]
Closing this issue since it seems to have stagnated and seems to be related to the packaging of some Thruk dependency (?) rather than naemon-core. Feel free to open a new issue if I'm mistaken.
