### ISSUE TITLE
Can't login into Naemon after install.

### ISSUE THREAD

**Issue by epx998** [naemon/naemon-core#118]
I followed the install guide (it's missing naemon-tools btw) and after the install was complete, the GUI comes up, however after entering admin with the password I set, I get nothing.  I just sit on the splash screen.  I tried a made up login and I get invalid login, but with the correct credentials I just stay at the splash, no errors.

Suggestions?

**Comment by catharsis** [comment]
You're probably better off filing this in the https://github.com/naemon/naemon tracker instead since naemon-core doesn't handle logins.
