### ISSUE TITLE
external command RESTART_PROGRAM with comments

### ISSUE THREAD

**Issue by VladimirBilik** [naemon/naemon-core#119]
Hi,
I would like to put a comment for external command "RESTART_PROGRAM", just for information why someone/something have issued it. Is it possible to add it as parameter in this command please?

BR,

Vladimir

**Comment by catharsis** [comment]
I realise this answer is very late, but here goes anyway;

We don't have any plans on adding this right now, no. However, if you really need it, you should be able to implement this yourself through a NEB module, making use of the `command_create`/`command_register` (https://github.com/naemon/naemon-core/blob/master/src/naemon/commands.h#L108) family of functions. The commands API is fairly stable, and I don't expect it change any time soon.

Depending on what you want to do with your comment, you could just either call the command handler for `RESTART_PROGRAM` or duplicate it within your module.
