### ISSUE TITLE
naemon not failing on "Error: Unexpected token or statement in file" in specific cases

### ISSUE THREAD

**Issue by bs-github** [naemon/naemon-core#124]
Naemon v1.0.3 tells you `Things look okay` even when it finds `Error: Unexpected token or statement in file` earlier in the `pre-flight check on configuration data` and exits with exit code 0.

This can lead naemon to run with significant chunks of your config missing which is a big problem.

Output on naemon -v naemon.cfg (the `Total Errors:   0` is the problem here):
```
Naemon Core 1.0.3-source
Copyright (c) 2013-present Naemon Core Development Team and Community Contributors
Copyright (c) 2009-2013 Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
License: GPL

Website: http://www.naemon.org
Reading configuration data...
   Read main config file okay...
Error: Unexpected token or statement in file '/tmp/simple-test.cfg' on line 58.
   Read object config files okay...

Running pre-flight check on configuration data...

Checking objects...
Warning: Service 'dummy' on host 'localhost' has no check time period defined!
Warning: Service 'dummy' on host 'localhost' has no notification time period defined!
	Checked 1 services.
	Checked 1 hosts.
	Checked 0 host groups.
	Checked 0 service groups.
Warning: Contact 'devnull' has no service notification time period defined!
Warning: Contact 'devnull' has no host notification time period defined!
	Checked 1 contacts.
	Checked 0 contact groups.
	Checked 1 commands.
	Checked 0 time periods.
	Checked 0 host escalations.
	Checked 0 service escalations.
Checking for circular paths...
	Checked 1 hosts
	Checked 0 service dependencies
	Checked 0 host dependencies
	Checked 0 timeperiods
Checking global event handlers...
Checking obsessive compulsive processor commands...
Checking misc settings...

Total Warnings: 4
Total Errors:   0

Things look okay - No serious problems were detected during the pre-flight check
```

To reproduce this you can use this example /tmp/simple-test.cfg (please note the `defin host {` line at the bottom - the misspelled define here should always lead to an error):
```
define command {
  command_name         dummy
  command_line         /bin/true
}
define host {
  name                 base
  register             0
  max_check_attempts   1
  check_command        dummy
  contacts             devnull
}
define host {
  use                  base
  host_name            localhost
  alias                localhost
  address              127.0.0.1
}
define service {
  name                 base
  register             0
  max_check_attempts   1
  contacts             devnull
}
define service {
  use                  base
  service_description  dummy
  check_command        dummy
  host                 localhost
}
define contact {
  name                            base
  register                        0
  host_notifications_enabled      0
  service_notifications_enabled   0
  can_submit_commands             1
  retain_status_information       0
  retain_nonstatus_information    0
  host_notification_commands      dummy
  service_notification_commands   dummy
  #host_notification_period        24x7
  #service_notification_period     24x7
}
define contact {
  use           base
  contact_name  devnull
  alias         Devnull Blackhole
}
defin host {
  use            base
  host_name      define-typo
  alias          define-typo
  address        127.0.0.1
}
```

Case 1 - if you include the config above in your naemon.cfg as follows naemon fails as it should:
```
cfg_file=/tmp/simple-test.cfg
```
```
...
   Error processing object config files!
...
```
Case 2 - if you include the config above in your naemon.cfg as follows naemon fails as it should:
```
cfg_file=/tmp/simple-test.cfg
cfg_dir=/tmp/emptydir
```
```
...
   Error processing object config files!
...
```
Case 3: if you include the config above in your naemon.cfg as follows **naemon is happy, but shouldn't**:
```
cfg_dir=/tmp/emptydir
cfg_file=/tmp/simple-test.cfg
```
```
...
Total Warnings: 4
Total Errors:   0
Things look okay - No serious problems were detected during the pre-flight check
...
```

**Comment by bs-github** [comment]
Nobody cares? 😞😟😭

At least quite easy to work around with a grep on the output of ```naemon -v``` in ```$TMPFILE```:
```
WARN=$(grep --count ^"[[:space:]]*Warning" "$TMPFILE")
ERR=$(grep --count ^"[[:space:]]*Error" "$TMPFILE")
```

**Comment by nook24** [comment]
I guess best work around is to use
````
cfg_dir=/opt/naemon/etc/config
cfg_dir=/etc/naemon/naemon.cfg.d
````
in your naemon.cfg an place your configs into the directories.

Than naemon will notice the error on startup and -v:
````
Error: Unexpected token or statement in file '/opt/naemon/etc/config/foobar.cfg' on line 48.
   Error processing object config files!


***> The name of the main configuration file looks suspicious...

     Make sure you are specifying the name of the MAIN configuration file on
     the command line and not the name of another configuration file.  The
     main configuration file is typically '/etc/naemon/naemon.cfg'
````

**Comment by bs-github** [comment]
@nook24 how is your answer related to the error case described in case 3 above?

**Comment by nook24** [comment]
@bs-github 
This is just an idea for a work around for your issue.
If you are include broken configuration files direct in naemon.cfg (your case 3) like this (foobar.cfg is the broken file you posted above):
````
cfg_dir=/opt/naemon/etc/config
cfg_dir=/etc/naemon/naemon.cfg.d
cfg_file=/opt/naemon/foobar.cfg
````

bin/naemon -v etc/naemon.cfg will say everything is ok:
````
Total Warnings: 4
Total Errors:   0

Things look okay - No serious problems were detected during the pre-flight check
````

But it's not! Your naemon restart command also will be happy:
````
$service naemon restart
Running configuration check...done
Stopping network monitor: naemon
Waiting for naemon to exit . . done.
Starting network monitor: naemon
````
But there is no naemon process running, due to your configuration is broken:
````
ps -eaf |grep naemon
root      7046  3319  0 16:38 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn naemon
````

So if you just include a directory inside of your naemon.cfg, naemon will notice the error with -v:
````
Error: Unexpected token or statement in file '/opt/naemon/etc/config/foobar.cfg' on line 48.
   Error processing object config files!
````

And also throw an error if you try to restart the process:
````
$service naemon restart
Running configuration check... FAILED!  Restart aborted.  Check your Naemon configuration.
````

**Comment by catharsis** [comment]
@bs-github First of all, sorry to have kept you waiting; we've got quite the backlog to catch up on here. We do care, and we do appreciate you taking the time to report any issues that you find.

Secondly, I'm currently not able to reproduce your case 3 on the latest git-version:

    ...
    cfg_dir=/tmp/emptydir #just an empty directory
    cfg_file=/tmp/simple-test.cfg #a direct copy of your sample
    ...

With this, I get `Error: Unexpected token or statement in file '/tmp/simple-test.cfg' on line 48.` and `
  Bailing out due to one or more errors encountered in the configuration files. Run Naemon from the command line with the -v option to verify your config before restarting. (PID=16422)` when running without `-v` and:

    
    Warning: check_result_path is deprecated and will be removed. Support for processing check results from disk will be removed
       Read main config file okay...
    Error: Unexpected token or statement in file '/tmp/simple-test.cfg' on line 48.
       Error processing object config files!


    ***> One or more problems was encountered while processing the config files...

     Check your configuration file(s) to ensure that they contain valid
     directives and data definitions.  If you are upgrading from a previous
     version of Naemon, you should be aware that some variables/definitions
     may have been removed or modified in this version.  Make sure to read
     the HTML documentation regarding the config files, as well as the
     'Whats New' section to find out what has changed.

when running with `-v`.

Just to avoid me closing this without having understood the issue; is anyone else able to reproduce this against the current master branch?

**Comment by bs-github** [comment]
@catharsis I can confirm, that the naemon compiled from the master branch is working fine in case 3. Say: it is bailing out with that broken config file.
```
Naemon Core 1.0.3-gf730f72
...
Error: Unexpected token or statement in file '/tmp/simple-test.cfg' on line 58.
...
$ echo $?
1
```
This is a :+1: for a new release or a bugfix release from me therefore.
