### ISSUE TITLE
naemon(1.0.4) cannot load module mod_gearman2(2-2.1.5-1) not loading with 

### ISSUE THREAD

**Issue by dannyjohn** [naemon/naemon-core#136]
Hello,

I have just tried naemon 1.0.4 from the consol labs repo in our dev environment.  Naemon fails to start with the message.

/var/log/naemon/naemon.log
 [1465184045] Error: Could not load module '/usr/lib64/mod_gearman2/mod_gearman2.o' -> /usr/lib64/mod_gearman2/mod_gearman2.o: undefined symbol: clear_volatile_macros
[1465184045] Error: Failed to load module '/usr/lib64/mod_gearman2/mod_gearman2.o'.
[snip]
[1465184045] Error: Module loading failed. Aborting.

OS: Red Hat Enterprise Linux Server release 7.2 (Maipo)
naemon: 1.0.4
mod_gearman2: 2.1.5-1

Is their any other information I can supply?  Regards, Danny

[naemon.zip](https://github.com/naemon/naemon-core/files/299723/naemon.zip)

**Comment by catharsis** [comment]
`clear_volatile_macros` is no longer part of the public Naemon API. Are you using a version of `mod_gearman2` that is built for Naemon compatibility? I'm not too familiar with `mod_gearman2` myself, but I'm sure this is easy enough for Sven to troubleshoot.

@sni Thoughts?

**Comment by sni** [comment]
You have to use mod_gearman3. It's not yet released, but there is a preview version available here: http://mod-gearman.org/download/v3.0.0b1/

**Comment by catharsis** [comment]
Thanks @sni! I'm closing this. Thanks for the report @dannyjohn :-)
