### ISSUE TITLE
Naemon 1.04 Centos won't send any notification

### ISSUE THREAD

**Issue by majales** [naemon/naemon-core#137]
Hi,
I've installed Naemon 1.04 from consol labs repo on my Centos7 server and I couldn't send any notificatios despite naemon claims in debug he sent them.

<pre>
cat /var/lib/naemon/naemon.debug
..
[Sat Jun  4 20:22:05 2016.155755] [032.0] [pid=29642] ** Service Notification Attempt ** Host: 'test.domain.local', Service: 'Check MariaDB Cluster Size', Type: CUSTOM, Options: 2, Current State: 0, Last Notification: Thu Jan  1 01:00:00 1970
[Sat Jun  4 20:22:05 2016.155780] [032.1] [pid=29642] This is a forced service notification, so we'll send it out.
[Sat Jun  4 20:22:05 2016.155786] [032.0] [pid=29642] Notification viability test passed.
[Sat Jun  4 20:22:05 2016.155801] [032.1] [pid=29642] Current notification number: 0 (changed)
[Sat Jun  4 20:22:05 2016.155840] [032.2] [pid=29642] Creating list of contacts to be notified.
[Sat Jun  4 20:22:05 2016.155848] [032.1] [pid=29642] Service notification will NOT be escalated.
[Sat Jun  4 20:22:05 2016.155853] [032.1] [pid=29642] Adding normal contacts for service to notification list.
[Sat Jun  4 20:22:05 2016.155857] [032.2] [pid=29642] Adding members of contact group 'admins' for service to notification list.
[Sat Jun  4 20:22:05 2016.155862] [032.2] [pid=29642] ** Checking service notification viability for contact 'myuser'...
[Sat Jun  4 20:22:05 2016.155867] [032.1] [pid=29642] This is a forced service notification, so we'll send it out to this contact.
[Sat Jun  4 20:22:05 2016.155870] [032.2] [pid=29642] Adding contact 'myuser' to notification list.
[Sat Jun  4 20:22:05 2016.155887] [032.2] [pid=29642] ** Notifying contact 'myuser'
[Sat Jun  4 20:22:05 2016.155901] [032.2] [pid=29642] Raw notification command: /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $LONGDATETIME$\n\nAdditional Info:\n\n$SERVICEOUTPUT$\n" | /usr/bin/mail -s "** $NOTIFICATIONTYPE$ Service Alert: $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$
[Sat Jun  4 20:22:05 2016.155955] [032.2] [pid=29642] Processed notification command: /usr/bin/printf "%b" "***** Nagios *****\n\nNotification Type: CUSTOM\n\nService: Check MariaDB Cluster Size\nHost: Devel Primary Database Server\nAddress: 192.168.100.50\nState: OK\n\nDate/Time: Sat Jun 4 20:22:05 CEST 2016\n\nAdditional Info:\n\nOK wsrep_cluster_size = 2\n" | /usr/bin/mail -s "** CUSTOM Service Alert: Devel Primary Database Server/Check MariaDB Cluster Size is OK **" myuser@gmail.com
[Sat Jun  4 20:22:05 2016.156022] [032.0] [pid=29642] 1 contacts were notified.
</pre>

But there is no trace of calling mail in /var/log/maillog
I even tried to change notification command to just simply create file in /tmp but no luck.

After downgrading to Naemon 1.03 everything OK and notification working again.

**Comment by SteveLowe** [comment]
I am seeing the exact same problem with 1.0.4 on CentOS 6

**Comment by catharsis** [comment]
Thanks for the report!

Okay, so at least the notification logic (whether to send notifications out or not) is working as expected.

If I had to guess, I'd say we're seeing an issue either with parsing the actual notification command or executing it. I have a feeling I've seen/heard about something much like this before. I'll do some digging.

**Comment by catharsis** [comment]
@majales I think you're experiencing https://jira.op5.com/browse/MON-8090. In short, try adding the `-Ssendwait` option to `/usr/bin/mail` in your notification command to force synchronous mail delivery.

Please let me know if that resolves your issue.

**Comment by GerasDraugas** [comment]
-Ssendwait helps for me. Naemon 104, Centos 6, openVZ container.

**Comment by djzort** [comment]
Same problem on debian 8.5 (in openvz). -Ssendwait fixed it

**Comment by catharsis** [comment]
Fixed by 615ca32.
