### ISSUE TITLE
bug: parents directive ignored in service object

### ISSUE THREAD

**Issue by parito** [naemon/naemon-core#151]
Configuration:

```
Debian 8
Naemon Core 1.0.5-pkg
mod-gearman-module 3.0.0b2 + gearman-job-server 1.0.6-5

```

In naemon documentation, _parents_ directive in service object states:

> This directive is used to define a comma-delimited list of short names of the "parent" services for this particular service. Parent services are typically other services that need to be available in order for a check of this service to occur. For example, if a service checks the status of a disk using SSH, the disk check service would have the SSH service as a parent. If the service has no parent services, simply omit the "parents" directive. More complex service dependencies may be specified with service dependency objects. 

See sample configuration used in testing:
[sampleconfiguration.txt](https://github.com/naemon/naemon-core/files/517886/sampleconfiguration.txt)

When defined, the service (disk, in this example) being actively checked regardless of the state of parent service. 

When the service **check-host-alive** is DOWN and in HARD state, the **disk** service is still being checked and reports it's status

**Comment by sponkydive** [comment]
hi,
parents for service is a new and naemon only config-parameter.
it works the same way like host parent/child relation.
It should only suppress notifications.
More info here: http://www.naemon.org/documentation/usersguide/config-incompat3to4.html
To avoid execution of a service in relation to another serivce use service_dependencies instead.
