### ISSUE TITLE
SCHEDULE_HOSTGROUP_HOST_DOWNTIME

### ISSUE THREAD

**Issue by Neurobion** [naemon/naemon-core#159]
Using 'Schedule downtime for all hosts in this host-group' does result in the log entry:

> Dec  8 07:23:55 server naemon: Warning: External command parse error [1481180834] SCHEDULE_HOSTGROUP_HOST_DOWNTIME;Environment-X;1481180834;1481181168;1;0;3600;admin;This is an example comment. (Invalid value)
> Dec  8 07:23:55 server naemon: External command error: Invalid value
> 

Invoked by command:
http://www.naemon.org/documentation/developer/externalcommands/schedule_hostgroup_host_downtime.html
`printf "[%lu] SCHEDULE_HOSTGROUP_HOST_DOWNTIME;Environment-X;1481180834;1481181168;1;0;3600;admin;This is an example comment.\n" `date +%s` > /var/lib/naemon/naemon.cmd`

```
START_DATE=`date +%s`
END_DATE=`date -d "+ ${MINUTES} minutes" +%s`
```

I'm using Version: 1.0.3 running on Ubuntu 12.04.5 LTS

**Comment by sni** [comment]
Could you retry with the latest release? The 1.0.3 is quite old already.
