### ISSUE TITLE
Service check timeout output string has an unnecessary extra newline

### ISSUE THREAD

**Issue by mpihelgas** [naemon/naemon-core#168]
This issue was actually reported for Nagios 4.0.6 by me (http://tracker.nagios.org/view.php?id=608) and fixed for Nagios 4.0.7, but I ran into the same issue with Naemon 1.0.6 now, so it seems that this fix was not carried over to Naemon.

The issue (and fix) is simple and caused by line 442 in naemon-core/src/naemon/checks_service.c

`nm_asprintf(&temp_service->plugin_output, "(Service check timed out after %.2lf seconds)\n", temp_service->execution_time);`

The newline (\n) at the the end of plugin output is inconsistent with other such outputs and breaks the log lines when I am using a custom logging format with the $SERVICEOUTPUT$ macro.

Essentially the fix would be to remove the newline, so that the output would be consistent everywhere.

**Comment by fmikker** [comment]
Thanks for pointing this out @mpihelgas !

@tvestelind Can you take a look at this and see if this still applies?

**Comment by tvestelind** [comment]
Hi,

First of all, thank you for submitting this.

Yes, it seems like this print is not consistent with the equivalent for host_check. I'll make the change and submit a PR.

**Comment by tvestelind** [comment]
Fixed in this commit: 6429af122ef90415fcb1c831e56004d12975d414

Please double check so that I made the right change :)

Thanks!

**Comment by mpihelgas** [comment]
Hi,
Looks good. Thanks!
