### ISSUE TITLE
Error: Unable to write to temp_path ('/var/cache/naemon') - Warning: Unable to write to check_result_path ('/var/lib/naemon/spool

### ISSUE THREAD

**Issue by Payden-Pringle** [naemon/naemon-core#183]
Hello, 

I'm getting the following error when Naemon's service attempts to start via SystemD on an Arch Linux installation. Note: httpd is the host name of the machine.

```
May 26 10:56:55 httpd naemon[8751]: Error: Unable to write to temp_path ('/var/cache/naemon') - P
May 26 10:56:55 httpd naemon[8751]: Warning: Unable to write to check_result_path ('/var/lib/naemon/spool
May 26 10:56:55 httpd naemon[8751]: Total Warnings: 1
May 26 10:56:55 httpd naemon[8751]: Total Errors:   1
```

System Specs:
```
[root@httpd /]# uname -a
Linux httpd 4.10.15-200.fc25.x86_64 #1 SMP Mon May 8 18:46:06 UTC 2017 x86_64 GNU/Linux
```

This is a fresh install of the following things, from a fresh install of the OS:
```
apache 2.4.25-3
php 7.1.5-1
php-apache 7.1.5-1
php-cgi 7.1.5-1
php-fpm 7.1.5-1
php-gd 7.1.5-1
php-snmp 7.1.5-1
thruk 2.14.2-4
```
Permissions of those two directories:
```
[root@httpd /]# ls -lha /var/cache/naemon/checkresults/
total 0
drw-rw-r-- 1 naemon naemon  0 May 25 08:55 .
drw-rw-r-- 1 naemon naemon 32 May 25 10:41 ..
[root@httpd /]# ls -lha /var/lib/naemon/spool
total 0
drwxr-x--- 1 naemon naemon  24 May 25 08:55 .
drwxr-x--- 1 naemon naemon 136 May 26 10:56 ..
drw-rw-r-- 1 naemon naemon   0 May 25 10:41 checkresults
```
I gave the group read and write permissions because `thruk` was running through the `http` user, which is in the `naemon` group. I had changed the user that `thruk` runs as to `naemon` as an attempt to solve the issue.

```
[root@httpd /]# groups http
naemon http
[root@httpd /]# groups naemon
naemon
[root@httpd /]# cat /etc/thruk/thruk_local.conf
############################################
# put your own settings into this file
# settings from this file will override
# those from the thruk.conf
############################################

thruk_user=naemon
thruk_group=naemon
```

However, even trying to start the `naemon` service via the following command from the terminal results in the error:

```
[root@httpd /]# systemctl start naemon
```

So I don't believe it's a `thruk` issue. I had just discovered the issue in `thruk`, then moved to trying it on the command line.

The service started fine the first time, but it was after attempting to configure things through the `thruk` interface, then saving the configuration changes, that I saw this issue come up.

**Comment by Payden-Pringle** [comment]
This was an issue regarding permissions on the file directories. 

In Linux, a directory should have execute permissions, always. Adding execute to the directories fixed my issue.

**Comment by sni** [comment]
Thanks for the heads up.
