### ISSUE TITLE
Memory leak on date/time macros

### ISSUE THREAD

**Issue by sni** [naemon/naemon-core#189]
@dirtyren commented on [Tue Jun 13 2017](https://github.com/naemon/naemon/issues/71)

   I have been testing naemon 1.0.6  and in the two setups I have running, the naemon process leaks memory till the kernel stops it.
   Running valgrind to hunt the bug, I found out  that the leak occurs in grab_datetime_macro_r when resolving MACRO_SHORTDATETIME as the log bellow show:

==23105== 48 bytes in 1 blocks are definitely lost in loss record 10 of 39
==23105==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==23105==    by 0x4C50F88: nm_malloc (nm_alloc.c:27)
==23105==    by 0x4C4CBCB: **grab_datetime_macro_r** (macros.c:567)
==23105==    by 0x4C4D3B7: grab_macro_value_r (macros.c:1892)
==23105==    by 0x4C4E1A4: process_macros_r (macros.c:2345)
==23105==    by 0x4C51A36: notify_contact_of_host (notifications.c:1825)
==23105==    by 0x4C54142: host_notification (notifications.c:1374)
==23105==    by 0x4C341D0: handle_async_host_check_result (checks_host.c:981)
==23105==    by 0x4C34F68: handle_worker_host_check (checks_host.c:621)
==23105==    by 0x4C64D39: handle_worker_result (workers.c:164)
==23105==    by 0x4C84F56: iobroker_poll (iobroker.c:372)
==23105==    by 0x4C48F1D: event_poll (events.c:321)

  I tried to add free_macro = TRUE after calling **grab_datetime_macro_r** in **grab_macrox_value_r**, just to to get a SEGV in **process_macro_r** line 2411.
  Anyway, I talked with Sven on freenode and he suspects a leak on some macros that we use on our notifcation plugin. The same stack trace above happens for notify_contact_of_host and notify_contact_of_service.
   Its possible that the bug extends to all DATE macros, as none is freed, all type call the same function and allocate output buffer there, with free_macro = FALSE.

**grab_macrox_value_r** line 1883 in macros.c
case MACRO_LONGDATETIME:
case MACRO_SHORTDATETIME:
case MACRO_DATE:
case MACRO_TIME:
case MACRO_TIMET:
case MACRO_ISVALIDTIME:
case MACRO_NEXTVALIDTIME:

/* calculate macros */
result = grab_datetime_macro_r(mac, macro_type, arg1, arg2, output);
break;

   Tks and let me know anything  I can help with.

**Comment by dirtyren** [comment]
This pull should solve this leak. At least it did not show in valgrind anymore.
https://github.com/naemon/naemon-core/pull/191

**Comment by sni** [comment]
PR has been merged.
