### ISSUE TITLE
Allowing circular dependencies for hosts

### ISSUE THREAD

**Issue by tvestelind** [naemon/naemon-core#193]
Currently naemon checks that the configured hosts and their relationships form a Direct Acyclic Graph, i.e. there are no circular dependencies/loops in the host 'graph'.

We see a need to be able to have this on customer sites and there is a patch created by @pengi that allows us to setup hosts with circular dependencies here: https://github.com/pengi/naemon-core/commit/5d43214d0f44116b0a0b06b394f7642d45617511

What do you think about merging that patch but documenting very carefully that this flag is experimental and the consequences of allowing circular dependencies are not fully known?

**Comment by pengi** [comment]
There are a couple of commands that probably will fail, or lock the system. But that's the only parts I'm aware of that will be a problem.

I think all commands that's named "and propagate" will be infinite recursive then.

Simples solution is to, in the beginning, disable those when this flag is set. And push to the future to have a better way of identifying the objects hidden behind a node in a non-acyclic graph.

**Comment by tvestelind** [comment]
@sni what do you think?

**Comment by sni** [comment]
I guess this will introduce all sort of unexpected behaviour, so this should be a flag or better a config option. Besides that, i have no opinion, if you need it and implement it properly, sure, why not.

**Comment by tvestelind** [comment]
PR opened here: https://github.com/naemon/naemon-core/pull/199

**Comment by jacobbaungard** [comment]
Closing this issue as the PR was merged back in October 2017: https://github.com/naemon/naemon-core/commit/1688701b59bbf7d000c63ca96f2cc02f4f5d2d48
