### ISSUE TITLE
Modified attributes behavior

### ISSUE THREAD

**Issue by dirtyren** [naemon/naemon-core#203]
Hello,
I noticed that when I disable a active check, the modified_attribute does a inclusive OR (|) and is set to 2,which is all right, but, when I enable the active check, it again does a inclusive OR keeping the attribute value to 2.
   Should it not do a exclusive OR (^) to remove the notice that the check is disabled, setting it back to 0?
   So the modified_attribute variable would always signal which attributes are disabled in the running configuration.
   I taught that the modified_attributes would show which settings do not match with the configuration files and were changed in running time, but I noticed that it does not do that, it just shows that active checks was changed at some point and I don't know if it was enabled or disabled before.

   Tks.

**Comment by sni** [comment]
This has always been the case and there is an external command to reset this flag. A few notes about that topic are here: https://thruk.org/documentation/modified_attributes.html

**Comment by dirtyren** [comment]
Tks @sni , I didt know about the external command to reset it, this may work for what we need.
  Anyway, I still dont think that the flag is useful the way it is know, because of the fact that if you disable and enable something, the flag will be set and you dont really know if the setting was on or off before.

    Tks.

**Comment by sni** [comment]
The flag is useful, it remembers if the current state set by external commands should superseed the configured setting from the config file. I know its sometimes confusing and thats why we display the
modified attributes in Thruk and have a command to reset the flag.
But the flag only stores that the value has changed, not to which value. So there is no way to safely reset the flag.

**Comment by dirtyren** [comment]
Tks, I'm closing the issue.
