### ISSUE TITLE
Disable service checks when host down

### ISSUE THREAD

**Issue by duylong** [naemon/naemon-core#208]
Hi,

Nagios core integrates a option in order to disable service checks when host down: https://github.com/NagiosEnterprises/nagioscore/commit/05e1dda8ccaa9d633b22b11a555d67724930a3e7

Do you think we can integrate this feature? If not, is there an equivalent option?

**Comment by sni** [comment]
Sounds interesting, anybody wants that to port to naemon?

**Comment by jacobbaungard** [comment]
Closed by: https://github.com/naemon/naemon-core/pull/274
