### ISSUE TITLE
naemon 1.0.6 : FAIL: t-tap/test_timeperiods

### ISSUE THREAD

**Issue by mrdiago** [naemon/naemon-core#212]
on archlinux 
compiling naemon failed  on test_timeperiods

not ok 95 - There should be no next valid time, was Mon Nov  1 00:00:00 2038

#     Failed test (t-tap/test_timeperiods.c:main() at line 380)

**Comment by sni** [comment]
i guess this is fixed meanwhile. Please reopen if the issue still persists
