### ISSUE TITLE
host_notification_commands with non existing object in contact, leads to Segfault

### ISSUE THREAD

**Issue by ofalk** [naemon/naemon-core#213]
Hi!

If you have a contact definition like so:
define contact {
 contact_name xxx    
 host_notification_commands xxx
}

Naemon will segfault during configuration validation (and of course also if you try to start it).

If host_notification_commands is a valid object, everything is fine.

I took only a (very) short glimpse at the code and didn't see the bug, but I'm sure some gdb skilled dev can find it in a minute.

KR,
 Oliver

**Comment by fmikker** [comment]
I think this is inherited from the fork. Earlier you could not define objects that referenced to a non-existing object, not sure if this is a bug or if you should be able to reference non-existing objects.
@roengstrom  @tvestelind 
Any input here?

**Comment by ofalk** [comment]
It's totally fine that it doesn't work to if you reference a non-existing object, but it should error out with a meaningful error message, instead of segfaulting :-)

**Comment by roengstrom** [comment]
We'll have a look at this during this sprint.
