### ISSUE TITLE
naemon.spec systemd detection is wrong and fails for fedora >=26

### ISSUE THREAD

**Issue by olahaye74** [naemon/naemon-core#223]
This method is wrong and ignores fc >=26.
%if 0%{?el7}%{?fc20}%{?fc21}%{?fc22}%{?fc23}%{?fc24}%{?fc25}
%global use_systemd 1
%endif
%if 0%{?suse_version} >= 1315
%global use_systemd 1
%endif

=> The correct way to detect systemd is the following one:
%if %{?_unitdir:1}0
do systemd stuffs
%else
do the old fashion way
%endif
=> No need to define "use_systemd"

This method works on ALL rpm based distros and doesn't require maintenance.
Note: BuildRequires is even more simple:
%systemd_requires
if defined it adds the correct requirements. if not, it's because it's not a systemd sbased system

**Comment by olahaye74** [comment]
Here is a patch to naemon.spec that fixes most issues.
[naemon.spec.patch.txt](https://github.com/naemon/naemon-core/files/1950332/naemon.spec.patch.txt)
It also fixes the http/conf.d directory detection.

**Comment by sni** [comment]
thanks, we are in the progess of moving builds and packaging to OBS. https://build.opensuse.org/project/show/home:nierlein:daily for now and later here https://build.opensuse.org/package/show/server:monitoring/naemon
I already started with improving the spec during the last weeks but then again, had no time :)
I will have a look at your changes and will merge them on OBS. If it works, i will also create a packaging repository here.

**Comment by olahaye74** [comment]
Excellent :-)
glad to seen naemon is not dead :-)
I can help testing if you need.

**Comment by sni** [comment]
Thanks again, this should be fixed with 5289d84d
