### ISSUE TITLE
Naemon does not honor the flag use_retained_scheduling_info

### ISSUE THREAD

**Issue by jvigna** [naemon/naemon-core#224]
When a naemon reload/restart is done if this flag is set naemon should retain the scheduling of all services from before. While this is working in nagios-3.x, in naemon the scheduling is recalculated for all host/service checks. This will lead to a problem if more reloads are done as it may happen that services are not checked for a long time.

**Comment by jacobbaungard** [comment]
Closed by https://github.com/naemon/naemon-core/pull/259
