### ISSUE TITLE
naemon-1.0.6 fails to build using gcc v7 (Fedora-27)

### ISSUE THREAD

**Issue by olahaye74** [naemon/naemon-core#227]
make[2]: Entering directory '/root/rpmbuild/BUILD/naemon-1.0.6/naemon-core'
  CC       src/naemon/broker.lo
  CC       src/naemon/checks.lo
src/naemon/checks.c: In function 'process_check_result_queue':
src/naemon/checks.c:243:38: error: '__builtin___snprintf_chk' output may be truncated before the last format character [-Werror=format-truncation=]
   snprintf(file, sizeof(file), "%s/%s", dirname, dirfile->d_name);
                                      ^
In file included from /usr/include/stdio.h:862:0,
                 from src/naemon/checks.h:9,
                 from src/naemon/checks.c:1:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output 2 or more bytes (assuming 257) into a destination of size 256
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1881: src/naemon/checks.lo] Error 1
make[2]: Leaving directory '/root/rpmbuild/BUILD/naemon-1.0.6/naemon-core'
make[1]: *** [Makefile:1213: all] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/naemon-1.0.6/naemon-core'
make: *** [Makefile:21: naemon-core] Error 2

**Comment by olahaye74** [comment]
Sorry I did only check oipenned issues :-(
any schedule for next release?

**Comment by jacobbaungard** [comment]
No problem, and many thanks for the report, always appreciated!

I think the next release will happen this or next week. I'll leave this open until the release is ready.

**Comment by jacobbaungard** [comment]
1.0.7 has been released now!
