### ISSUE TITLE
No newline in some debug logs

### ISSUE THREAD

**Issue by jframeau** [naemon/naemon-core#247]
Extract

**[1531383499.208279]** [032.0] [pid=1967] SERVICE CONTACT NOTIFICATION SUPPRESSED: SupervisorFRHD;control;Notifications are disabled for this object by its configuration.**[1531383499.208811]** [032.0] [pid=1967] 3 contacts were notified.  Next possible notification time: Thu Jul 12 10:18:19 2018
[1531383501.118814] [032.0] [pid=1967] ** Service Notification Attempt ** Host: 'FRHD', Service: 'dwcontrol', Type: NORMAL, Options: 0, Current State: 2, Last Notification: Thu Jul 12 10:18:19 2018

Looking at log_debug_info calls, some have \n in their format string, some others no. That's the case with _log_nsr too.

Grepping source files with grep -rn log_debug_info * | grep "\.c" | grep -v "\\\\n" command displays many missing newlines.

But perhaps there are some reasons behind these missing newlines.

jfr

**Comment by sni** [comment]
i don't see a reason why the newline should be absent on purpose.

**Comment by sni** [comment]
Thanks for the pointer, the PR above should fix it.

**Comment by jframeau** [comment]
Ok, thx, patch applied. Debug logs look good now.
