### ISSUE TITLE
service_description allows commas but dependent_service_description does not

### ISSUE THREAD

**Issue by stromsoe** [naemon/naemon-core#253]
My service_description elements have commas.  I'm seeing parsing errors if the matching dependent_service_description elements have commas.

This:

```
define service {
    service_description a,b,c
}
define servicedependency {
    dependent_service_description a,b,c
}
```

is being parsed as

```
define service {
    service_description a,b,c
}
define servicedependency {
    dependent_service_description a
}
```

and is failing because there is no match.

Documentation for dependent_service_description states that it is a comma-separated multi-valued field.

There should be a way to escape embedded commas, or there should be a structured way to specify multi-valued that doesn't rely on legally embedded characters

**Comment by sni** [comment]
thats why `illegal_object_name_chars` contains commas by default. Please do not use commas in service descriptions.
