### ISSUE TITLE
service_check_timeout_state=u is not honored

### ISSUE THREAD

**Issue by bjornfro** [naemon/naemon-core#260]
When service check times out it seems CRITICAL is returned no matter if UNKNOWN is set in naemon.cfg by:

<pre>
# SERVICE CHECK TIMEOUT STATE
# This setting determines the state Naemon will report when a
# service check times out - that is does not respond within
# service_check_timeout seconds.  This can be useful if a
# machine is running at too high a load and you do not want
# to consider a failed service check to be critical (the default).
# Valid settings are:
# c - Critical (default)
# u - Unknown
# w - Warning
# o - OK
service_check_timeout_state=u
</pre>
This with Naemon 1.0.6.

**Comment by sni** [comment]
is this a plain naemon? Or is there for example mod-gearman involved?

**Comment by bjornfro** [comment]
Yes, mod-gearman is involved.

**Comment by sni** [comment]
mod-gearman does not have this feature and will return unknown on timeouts. You might want to open a feature request over at https://github.com/sni/mod_gearman

**Comment by bjornfro** [comment]
Ok, but I get critical as return code.

Regards, Björn

**Comment by bjornfro** [comment]
Oh, missed that feature.  I guess I should have found it. Thanks!
