### ISSUE TITLE
Config tool breaks multiple hostgroups

### ISSUE THREAD

**Issue by bakercr17** [naemon/naemon-core#288]
If a host definition requires to be in multiple hostgroups the config tool will quote the comma as such "hostgroup1','hostgroup2','hostgroup3".  Prior to 2.28 this did not cause issues however now the config test will fail and the daemon will not reload properly.  If I vim the config file and do a global search and replace of ',' with just a comma the daemon will reload properly.  However, the config tool will attempt to revert back to ',' whenever another change is attempted and once again the config test will fail.

**Comment by nook24** [comment]
Which config tool do you use? But you should ask the developers of the configuration tool why they generate a broken configuration :)

**Comment by bakercr17** [comment]
I'm thinking this issue might best be suited for the Thruk page since that is the config tool I am using.  I have opened a ticket there as well.

**Comment by sni** [comment]
closing this one, see https://github.com/sni/Thruk/issues/925
