### ISSUE TITLE
Which IDE do you use?

### ISSUE THREAD

**Issue by nook24** [naemon/naemon-core#292]
I'm not an professional C developer and it would be really great if you guys could provide some information which IDE and Debugger you use and how to setup an proper development environment. Most of the time when I patch around at the Naemon-Core I simply use print or the naemon.log.

My broker module is build with CMake. This allows me to use CLion which has great support for debugging. How ever, I have no experience with debugging autoconf projects in CLion...

Visual Studio is able to compile on Linux but I never used this.
I'm not addicted to an IDE or operating system.

Would be great if you could help me to setup an environment where I could set breakpoints and stuff like this.

**Comment by nook24** [comment]
I have to say set up a development environment for Naemon using Eclipse was easier than expected.

I've documented my solution for everyone else who is interested in, or finding this issue through a search engine.
https://statusengine.org/tutorials/setup-naemon-development-environment/

**Comment by sni** [comment]
Just for reference, i once created a vagrant box for easy development:
https://github.com/sni/naemon-dev-vagrant-box
It clones Thruk, Naemon, Livestatus and Mod-Gearman on a shared folder and creates 2 omd sites, `dev` and `mon`. The dev site uses the software fresh compiled from the shared folder and the mon site monitors memory and such things.
You then can use any IDE to work on naemon and related projects and directly watch your changes
in a test lab.

**Comment by nook24** [comment]
Good to know, thanks for your feedback.
