### ISSUE TITLE
/usr/include/naemon/naemon/ instead of /usr/include/naemon

### ISSUE THREAD

**Issue by dirtyren** [naemon/naemon-core#299]
Hello,

I was moving some apps from CentOS6 to  CentOS7 and I noticed that naemon-devel-1.0.6 installs its headers under /usr/include/naemon but the latest package 1.0.10 naemon-devel installs under /usr/include/naemon/naemon/ .

   If there any reason for this change?

  Tks.

**Comment by sni** [comment]
not intentionally, no.

**Comment by sni** [comment]
is that eh consol labs repo package or from the obs build server?

**Comment by dirtyren** [comment]
I built it from source from github  and it builds 1.0.10 like this, than I downloaded the RPM packages from naemon.org and it is the same.
   The build I do of my own naemon version based on 1.0.6 does not do thtat. I think this could have happened after the packages decoupling in 1.0.7.

   []s.

**Comment by dirtyren** [comment]
Same deal with the console labs repo pkgs, install under /usr/include/naemon/naemon/
