### ISSUE TITLE
Naemon: general protection ip

### ISSUE THREAD

**Issue by hkowallik** [naemon/naemon-core#308]
After months of excellent service naemon died last night with the following error

     Oct 12 01:11:43 naemon-host kernel: do_general_protection: 174 callbacks suppressed
     Oct 12 01:11:43 naemon-host kernel: traps: naemon[18068] general protection ip:7f7eadf3d4d3 sp:7f7eb164dac8 error:0 in libstdc++.so.6.0.19[7f7eadec8000+e9000]
     Oct 12 01:11:43 naemon-host systemd[1]: naemon.service: main process exited, code=killed, status=11/SEGV
     Oct 12 01:11:43 naemon-host systemd: naemon.service: main process exited, code=killed, status=11/SEGV
     Oct 12 01:11:45 naemon-host systemd[1]: Unit naemon.service entered failed state. 
     Oct 12 01:11:45 naemon-host systemd: Unit naemon.service entered failed state. 
     Oct 12 01:11:45 naemon-host systemd[1]: naemon.service failed.
     Oct 12 01:11:45 naemon-host systemd: naemon.service failed.

Environment is RHEL7 running on VMware.

Earlier that day the naemon host had two hiccups where it did not proceess any active checks.
The first time we got messages in the error log

     Unable to send check for service 'check' on host 'host' to worker (ret=-2)

The second time we simply have a gap in the log file and metrics show a sharp drop in the number of network connections.

These hiccups were "resolved" when we restarted naemon to activate updated configuration files.

Any idea what went wrong?
Anything I can/should do to analyze this further?

**Comment by sni** [comment]
Please try again with the latest 1.1.0 release, i believe this has been resolved meanwhile.
