### ISSUE TITLE
Timeout on random-string generation in plugin

### ISSUE THREAD

**Issue by it-native** [naemon/naemon-core#319]
Hi, 
when I try to create a random string in a plugin (bash) the script runs on bash but times out when run by naemon.
random-string()
{
    /bin/cat /dev/urandom | /bin/tr -dc 'a-zA-Z0-9' | /bin/fold -w ${1:-32} | /bin/head -n 1
}

here is the thread on the monitoring-portal: https://monitoring-portal.org/t/service-timed-out-but-working-in-th-shell/6790/2

BR
Oliver

**Comment by sni** [comment]
thanks, should be fixed with the PR above.
