### ISSUE TITLE
contact_groups in service object not inherited from host when contats are defined locally

### ISSUE THREAD

**Issue by topinet** [naemon/naemon-core#320]
OS: Debian 8
Naemon: 1.0.10

I have setup up host/services this way:
- host includes contact_group value
- service inherits contact_group value from host
- for a small set of services we notify another contacts, so these services include a contacts values.

Expected behaviour is those services (with contacs defined locally) is to notify contact_groups (inherited from host) and contacts (defined locally)

However, when contacts is defined locally, services don't inherit contact_groups from host.

Found similar bug in nagios-core:
https://github.com/NagiosEnterprises/nagioscore/issues/240

**Comment by nook24** [comment]
According to the devs this is the new wanted behavior... See the discussion in my PR #92

**Comment by sni** [comment]
Thats by design and how it works.
See http://www.naemon.org/documentation/usersguide/objectinheritance.html#implied_inheritance
```
the values of some service variables will be copied from the host the
service is associated with if you don’t otherwise specify them.
```

Or am i missing something?

**Comment by topinet** [comment]
According to http://www.naemon.org/documentation/usersguide/objectinheritance.html#implied_inheritance the expected behaviour is to inherit contact_groups from host, so this variable doesn't exists in service definition.

But, for any reason, inherintance of contact_groups is not done when contacts is defined for the service

**Comment by nook24** [comment]
Inheritance will only work as long as you don't define any contact OR contact group in the service definition.

So for me it looks like that the docs are missing the fact, that there is a condition when `contact_groups` gets inherited from the host.  Only as long as the service has no own contacts **and** contact groups.

I patched this 5 years ago but for some reason this is not how it is supposed to be.
Even if this was the default Nagios 3 behavior for years. ¯\\\_(ツ)\_/¯

**Comment by topinet** [comment]
Thanks for your answers.

Finally, I've modified NConf to add any contact_groups defined in parent host when contacts and/or contact_groups are defined locally in the service.
