### ISSUE TITLE
Timeperiod Exclude between two days

### ISSUE THREAD

**Issue by Pkysoarn** [naemon/naemon-core#327]
Hello , 
It's not exactly an issue but a confirmation about a possibility of timeperiod :
Is it possible while using exclude to manage a timeperiod between two days like :
friday          23:01-02:00
Without using two days , or should i put : 
friday 23:01-23:59
saturday 00:00-02:00 

The question is about gestion of exclude for week and week-end , and it would be great if it's possible . 

Thanks for the reply .

**Comment by sni** [comment]
No, thats not possible. The friday ends at `24:00`. You need to split that into 2 days.
