### ISSUE TITLE
Leftover retention.dat files

### ISSUE THREAD

**Issue by lamaral** [naemon/naemon-core#331]
Hey guys,

I noticed an increase in disk usage on my Naemon server. Upon investigation, I realized that there are quite a few retention.dat files leftover on the `/var/lib/naemon/` folder. 

```
-rw-------  1 naemon naemon 431M May 15 10:59 retention.dat
-rw-------  1 naemon naemon 430M May 13 16:21 retention.datzEmgCJ
-rw-------  1 naemon naemon 429M May 12 11:28 retention.dat8eKvnm
-rw-------  1 naemon naemon 387M May 11 17:25 retention.datz0hmJA
-rw-------  1 naemon naemon 426M May 11 14:57 retention.datqfHx2W
-rw-------  1 naemon naemon 425M May  7 16:03 retention.datYLcrTx
-rw-------  1 naemon naemon 426M May  6 16:19 retention.datLumtLX
-rw-------  1 naemon naemon 432M May  6 13:55 retention.dattiJs8p
-rw-------  1 naemon naemon 425M Apr 28 16:48 retention.datKGSnBq
-rw-------  1 naemon naemon 423M Apr 27 21:39 retention.datKP9xpt
-rw-------  1 naemon naemon 423M Apr 27 20:58 retention.dathTYkhz
-rw-------  1 naemon naemon 422M Apr 27 19:29 retention.datKd6kRm
-rw-------  1 naemon naemon 421M Apr 27 17:14 retention.dat1YuK45
-rw-------  1 naemon naemon 420M Apr 27 14:51 retention.datEaW3fH
-rw-------  1 naemon naemon 419M Apr 27 10:11 retention.datXth75K
-rw-------  1 naemon naemon 420M Apr 21 11:11 retention.datAmx0Ij
-rw-------  1 naemon naemon 252M Apr 20 14:07 retention.datiVTang
-rw-------  1 naemon naemon 424M Apr 16 09:14 retention.datPFD3nI
-rw-------  1 naemon naemon 424M Apr 15 14:24 retention.datoL83CG
-rw-------  1 naemon naemon 424M Apr 14 21:06 retention.datKFjuqC
-rw-------  1 naemon naemon 423M Apr 10 10:03 retention.datlmRlEC
-rw-------  1 naemon naemon 214M Apr  8 11:27 retention.datPS5QT3
-rw-------  1 naemon naemon 432M Apr  7 17:35 retention.dat5XMafk
-rw-------  1 naemon naemon 432M Apr  7 14:11 retention.datcAeImG
-rw-------  1 naemon naemon 433M Apr  6 20:59 retention.dat2lNeBI
-rw-------  1 naemon naemon 431M Apr  6 13:29 retention.datXBGQWo
-rw-------  1 naemon naemon 431M Apr  6 10:03 retention.datUcIzdA
-rw-------  1 naemon naemon 209M Apr  3 10:03 retention.datt4GBty
-rw-------  1 naemon naemon 429M Apr  1 16:13 retention.datfLKact
-rw-------  1 naemon naemon 430M Apr  1 10:03 retention.datKc3XUG
-rw-------  1 naemon naemon 428M Apr  1 09:21 retention.datjRKjtw
-rw-------  1 naemon naemon 236M Mar 30 15:07 retention.datFAS2In
-rw-------  1 naemon naemon 431M Mar 26 14:32 retention.dateUOlTl
-rw-------  1 naemon naemon 431M Mar 25 17:54 retention.datYcc71F
-rw-------  1 naemon naemon 431M Mar 25 14:57 retention.datWeEzRw
-rw-------  1 naemon naemon 431M Mar 20 13:45 retention.datdcYPwt
```

We are running Naemon 1.1.0 on Debian Stretch, with the packages from the Consol Labs repo. 

If you need any extra info, please let me know.

**Comment by lamaral** [comment]
After taking a closer look at https://github.com/naemon/naemon-core/blob/master/src/naemon/xrddefault.c, I think Naemon is getting restarted by our configuration generation tool while executing the `xrddefault_save_state_information()` function.

**Comment by sni** [comment]
A few things to consider:
- Most of those files seem to have an eqal size (with a few exceptions) Do those files seem to be completly written or do they suddenly end somewhere in the middle?
- Could you grep for `Error: Unable to `in your log archive? Are there any errors?
- Do the timestamps of those files correlate with reload/restarts?

**Comment by sni** [comment]
Found one leftover file here as well:
```
-rw------- 1 naemon naemon 225938 Apr 24 07:41 retention.datPP8Hfz
```
It seems to be completely written and the only suspicious log entry at that time is:
```
[2020-04-24 07:41:08] Warning: Host performance data file processing command '/bin/mv .../var/pnp4nagios/host-perfdata .../var/pnp4nagios/spool/host-perfdata.1587706845' timed out after 5 seconds
```
Which indicates some kind of io issue.

**Comment by lamaral** [comment]
Hi Sven,

I checked the leftovers I have currently (I had to clean up the ones from the initial message to free up some space) and they were completely written, except for two of them, which had a reduced size also. 

I grepped for the string you indicated and it's not found anywhere in my logs. I looked for errors around the timestamp of the files and couldn't spot anything. 

The restarts seem to happen without a problem:
```
[1590568574] Caught 'Terminated', shutting down...
[1590568590] Naemon 1.2.0 starting... (PID=12362)
[1590568590] Local time is Wed May 27 10:36:30 CEST 2020
[1590568590] LOG VERSION: 2.0
```

The timestamps of the files are a few seconds away from the restart requests from our sysadmins, and match the exact time that our configuration generation tool called the restart of Naemon. 

I have also upgraded our Naemon to version 1.2.0 and the problem is also present there.

**Comment by sni** [comment]
Is this the stock init script? Naemon writes the rentention file usually every 60 minutes or on a shutdown/restart. Probably on reloads as well. Since you are talking about restarts, are
there any timeouts in your shutdown process?

**Comment by lamaral** [comment]
Ah, good point.

We have a custom systemd service unit, but it doesn't differ much from the one at https://github.com/naemon/naemon-core/blob/master/daemon-systemd.in.

```
[Unit]
Description=Naemon Monitoring Daemon
After=network.target

[Service]
LimitNOFILE=10000
PermissionsStartOnly=true
User=naemon
Group=naemon
Environment='TZ=:/etc/localtime'
Type=forking
PIDFile=/run/naemon/naemon.pid
ExecStart=/usr/bin/naemon -d /etc/naemon/naemon.cfg
UMask=0022
PrivateDevices=false
ProtectHome=false
Restart=always

[Install]
WantedBy=multi-user.target
```

We stripped away the ExecStartPre because our config generation tool takes care of testing the config before copying it over to `/etc/naemon`.
The missing ExecReload shouldn't cause problems as our tool always restarts Naemon, but I'll add it to be safe. 

Looking at some systemd docs, it seems that the default stop timeout is set to 90 seconds. So systemd will first send a SIGTERM and if after 90 seconds, the daemon haven't stopped, it will send a SIGKILL. Could it be that a heavy livestatus query or something else is preventing Naemon from stopping before the timeout?

**Comment by lamaral** [comment]
Turns out I missed some things in May when I first investigated this. 
We are using the Debian Buster package from the Consol repository and turns out that Naemon was actually using the initd script instead of the systemd unit in our system.
The systemd unit I reproduced in the previous message, was misconfigured via Puppet and ended up never being applied (the file got created as naemon.service.service).

After I removed the initd script and applied the systemd unit correctly, the problem seems to be gone. We have two identical instances and the one using the systemd unit has not suffered from this problem so far, while the one with initd has had a few occurrences. 

Was it intended that the Debian packages use initd instead of systemd?

**Comment by sni** [comment]
> Was it intended that the Debian packages use initd instead of systemd?

Definitly not, naemon should use the standard init system available.

**Comment by sni** [comment]
debian systemd integration should be fixed with https://github.com/naemon/naemon-core/pull/339

**Comment by lamaral** [comment]
Thank you very much, Sven!

After running the master for a couple days with the Systemd unit in place and the initd script removed, no leftover files showed up, so I believe that's solved.

**Comment by sni** [comment]
i don't think you need to remove the initd script. Debian will prefer the service file if its there.
Anyway, great its working out now.
