### ISSUE TITLE
retain acknowledgment after restart

### ISSUE THREAD

**Issue by redlegoman** [naemon/naemon-core#349]
I'm not sure if I've missed something or if this is the expected behavour:
If I acknowledge a "down" server then restart naemon, the acknowledgement is lost after restart - is there a way to retain this acknowledgement after a restart? Using sticky ack or and sticky comment didn't seem to help.
I am running naemon core 1.2.2 and thruk 2.38-2 on Ubuntu

**Comment by sni** [comment]
That should not be the case, acknowledgements are retained in the retention.dat file over restarts. Could you check if the acknowledgement is in that file.

**Comment by jacobbaungard** [comment]
Also make sure that `retain_state_information` and possibly `use_retained_program_state` are not set to `0` in your conf file. They both should be `1` by default, but you can also try setting them explicitly.

**Comment by redlegoman** [comment]
Thanks. It turns out that naemon only writes the retain.dat on clean exit. I'm running naemon in a docker container and when docker stops, it doesn't cleanly stop naemon, it just kills it so naemon doesn't write the retention.dat. I got round this by copying state.dat to retention.dat just before starting naemon in the entrypoint script for my docker container. A bit of a bodge, but it works until I can work out how to get docker to cleanly stop naemon. It would be kind of nice if naemon wrote out retention.dat on a regular basis and there was a config paramater to define the period, like there is with state.dat.

**Comment by sni** [comment]
You are looking for `retention_update_interval`

```
# RETENTION DATA UPDATE INTERVAL
# This setting determines how often (in minutes) that Naemon
# will automatically save retention data during normal operation.
# If you set this value to 0, Naemon will not save retention
# data at regular interval, but it will still save retention
# data before shutting down or restarting.  If you have disabled
# state retention, this option has no effect.

retention_update_interval=60
```

https://www.naemon.org/documentation/usersguide/configmain.html#automatic_state_retention_update_interval

**Comment by redlegoman** [comment]
Ah! That's perfect, thanks. Can't believe I couldn't find that option myself. I thought I had read every word in naemon.cfg already!

**Comment by jacobbaungard** [comment]
A tip is to use Tini (https://github.com/krallin/tini) so that signals are correctly forwarded to Naemon on container shutdown.
