### ISSUE TITLE
Very slow start up of Naemon if a system has many downtimes

### ISSUE THREAD

**Issue by nook24** [naemon/naemon-core#374]
Hi,

I found an issue within Naemon which will occur as soon as the system has to handle thousands of downtimes. In this case a restart of Naemon takes more than 15 minutes.

```
# cat retention.dat | grep hostdowntime | wc -l
21127

# cat retention.dat | grep servicedowntime | wc -l
294420
```

The  issue is caused by the `find_comment` function
https://github.com/naemon/naemon-core/blob/47002195d849455863c2fad7f1a440192ef6cce5/src/naemon/comments.c#L640-L650

My suggestion is to replace this with an hashmap.

**Comment by nook24** [comment]
I guess this will be resolved with https://github.com/naemon/naemon-core/pull/440 ?@sni

**Comment by sni** [comment]
that's right.
