### ISSUE TITLE
Please provide builds voor Debian 11

### ISSUE THREAD

**Issue by roelvanmeer** [naemon/naemon-core#378]
Hi!

Now that Debian 11 is stable, it would be nice to have Naemon builds for it as well. Is it possible to set this up?
I've verified that the current master branch builds on Bullseye without any problems, so I don't expect any dependency problems.
I'm also willing and able to help if that's appreciated.

Kind regards, Roel

**Comment by roelvanmeer** [comment]
That was quick, thanks!

**Comment by sni** [comment]
well, if it buids without issues, its really just 2 clicks in the obs website. I just tend to forget adding new distros.
Packages should be ready meanwhile.
