### ISSUE TITLE
Bash expressions in init.d file which runs with #!/bin/sh

### ISSUE THREAD

**Issue by xavier8854** [naemon/naemon-core#406]
Hi,
In start() function, ther is a bashism
 `if [ "x${is_suse}" == "xyes" ]`
which triggers an error because the shebang is #/!bin/sh. Changing to /bin/bash fixes the problem :
`RUN sed -i 's/\/bin\/sh/\/bin\/bash/' /etc/init.d/naemon`
I know that init scripts **must** be POSIX compliant, but in this case, it is not
HTH
Xavier

**Comment by sni** [comment]
thanks. Above PR should fix this and a few others found by `checkbashisms`.
