### ISSUE TITLE
Issues with Business Process

### ISSUE THREAD

**Issue by Kevin-McKee** [naemon/naemon-core#460]
I'm using the Business Process plugin within Naemon/Thruk, and have previously been able to edit/save the processes successfully. More recently - and I don't know if it's a result of patches applied to my system, I'm now getting an error when trying to save a business process.

![IoKss](https://github.com/naemon/naemon-core/assets/41024587/2c36752f-e3e6-47c0-8b28-4d0638497b21)

The only additional thing I see in my thruk.log file is

`Naemon: 491: failed to connect - failed to connect to localhost:7003: Connection refused. at /usr/share/thruk/lib/Thruk/Backend/Manager.pm line 1598`

I'm not really sure where to start troubleshooting this issue - if anybody has any tips, I'd appreciate the help. Thanks

**Comment by sni** [comment]
Probably more a Thruk issue....
Thruk needs to restart naemon when saving new business processes. If everything is ok when you
refresh the page, then this might be a race condition during the short period where naemon is "offline" and reloading the configuration.

**Comment by Kevin-McKee** [comment]
Refreshing the page continues to bring up the same error.  I will create an issue with Thruk
