### ISSUE TITLE
1.4.2 duplicate contact

### ISSUE THREAD

**Issue by bjornfro** [naemon/naemon-core#461]
Did a test upgrade from 1.3.0 to 1.4.2. Now I get complaints about duplicate contacts. Cannot really find these duplicates though. Any clue?

/usr/bin/sudo -u naemon /usr/bin/naemon -v /etc/naemon/naemon.cfg

Naemon Core 1.4.2
Copyright (c) 2013-present Naemon Core Development Team and Community Contributors
Copyright (c) 2009-2013 Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
License: GPL

Website: https://www.naemon.io
Reading configuration data...
   Read main config file okay...
Warning: Duplicate definition found for contact 'generic-contact' (config file '/etc/naemon/conf.d/templates/contacts.cfg', starting on line 8)
Error: Could not add object property in file '/etc/naemon/conf.d/templates/contacts.cfg' on line 9.
   Error processing object config files!

**Comment by sni** [comment]
Could you provide a minimal configuration which triggers this issue?

**Comment by bjornfro** [comment]
Sorry, my bad, it was including a sub-directory named conf.d-not-used that I missed.

**Comment by sni** [comment]
no worries, glad you found the issue
