### ISSUE TITLE
SOFT states on max_check_attempts=1

### ISSUE THREAD

**Issue by white-line** [naemon/naemon-core#473]
As far as I know, with "max_check_attempts=1" there should only be HARD states - that is, the check should be performed only once.

configuration:
![изображение](https://github.com/user-attachments/assets/da2ad825-67c7-4938-ad63-59d83728ac0d)

extinfo page:
![изображение](https://github.com/user-attachments/assets/c746512d-b6e1-45b6-9b16-1afa52969912)

event log:
![изображение](https://github.com/user-attachments/assets/d92216dd-7a89-4a55-b5e9-7eb8daae00e3)

In the event log you can see that there were two checks with an interval of 1 minute ( retry_interval=1 ( 60 seconds )).

reproduced on OMD 5.40-labs-edition.

**Comment by white-line** [comment]
In naemon docs:
![изображение](https://github.com/user-attachments/assets/cdb3a4d9-11dd-433b-ba3f-370bff6a4992)

**Comment by sni** [comment]
wondering if this is due to the parent being down. On the other hand, the docs are very clear here and i don't see any reason why this should not be an immediate hard state change.
