### ISSUE TITLE
Can't get availability reports working

### ISSUE THREAD

**Issue by fermino** [naemon/naemon-core#485]
I don't know if maybe I'm doing something totally wrong or if I just didn't understand something, but I'm having issues using availability reports. 

My setup is a thruk instance conected through livestatus to 6 naemon instances distributed in various hosts. 
Whenever I generate an availability report, all the hosts that have been stable for some time show 100% indeterminate time, even when they have been alive for all that time. As a side note, I can't force-set the initial state as it could be either up/down and I need the reports to reflect the actual status. 

Going through the docs what I understand is that `avail.cgi` uses the logs in `log_archive_path` to generate those reports, but I can't find ANY logs in my systems, and going through the code I found that naemon [doesn't actually use that variable](https://github.com/search?q=repo%3Anaemon%2Fnaemon-core+path%3A%2F%5Esrc%5C%2F%2F+log_archive_path&type=code)?

I'm pretty sure I missed some notes in the config, but I'm a bit lost where to look. 
Any help is appreciated, thanks :)

**Comment by sni** [comment]
It's true. Naemon does not use that variable anymore, we rotate logfiles with the logrotate daemon like any other sane daemon.
But... livestatus does use that variable and looks for older logfiles there.
See: https://github.com/search?q=repo%3Anaemon%2Fnaemon-livestatus+path%3A%2F%5Esrc%5C%2F%2F+log_archive_path&type=code
And Thruk uses livestatus to get the log data.

**Comment by fermino** [comment]
Thank you!

If I'm following it right that means that availability reports will only get info in the log archive (and whatever is in memory?), right?

Is there any specific format the archived logs should follow? I have tried looking it up in the code but I couldn't really find it.

**Comment by sni** [comment]
the archive uses the same format as the "normal" logfile, it's just that they are moved into a separate folder.

**Comment by fermino** [comment]
Silly me wasn't rotating the logs and that's why the reports were empty :rofl: 
Thank you!!
