### ISSUE TITLE
small RPM issues

### ISSUE THREAD

**Issue by liedekef** [naemon/naemon-core#60]
Using the RPM build version 0.8.1_20140415 , it seems there are some issues:

- /var/run/naemon is not being created, so the default configured PID can't be stored and thus naemon refuses to launch
- if there are just warnings in the config files, naemon tells you it is ok, but the init script refuses to start naemon if warnings are found

**Comment by catharsis** [comment]
I believe this is fixed. I'm closing this issue, but feel free to reopen it if I'm mistaken. Thanks for reporting it, and sorry for the late response!
