### ISSUE TITLE
RPMs require shadow-utils on OpenSuSe 13.1 but there's no such package

### ISSUE THREAD

**Issue by mfrost8** [naemon/naemon-core#63]
Building the RPMs from source result in a dependence on the "shadow-utils" package by the base naemon rpm.   This package does not exist on OpenSuse (at least version 13.1).

The utilities provided by shadow-utils on other redhat flavors appear to be provided by the "shadow" package on OpenSuse.

**Comment by catharsis** [comment]
Not sure if this is still an issue, but I feel like it might not be since this hasn't been touched in ~2 years. It also seems to be related to packaging rather than naemon-core, so I'm closing this.
