### ISSUE TITLE
warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS'

### ISSUE THREAD

**Issue by berendt** [naemon/naemon-core#7]
On a SLES11 SP3 I got the following warnings while running autoreconf -i (autoconf-2.69-40.1).

```
naemon/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
naemon/lib/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
```

**Comment by rebroad** [comment]
so, what is the solution?

**Comment by danielcoringa** [comment]
Simple: 
#./configure US_CPPFLAGS="-03"

**Comment by wujinghust** [comment]
plugins/Makefile.am:14: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
plugins/Makefile.am: installing './depcomp'
tests/Makefile.am:13: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

there are two warning  when I install  tslib.So,what should I do?
