### ISSUE TITLE
remote ansible restart won't start

### ISSUE THREAD

**Issue by kakbit** [naemon/naemon-core#81]
I've noticed a peculiar thing when trying to restart the naemon service on RHEL6 with (latest pip) ansible.
The naemon service will stop but it won't start unless restarting twice.
When running restart on the actual naemon server the service will restart as expected.
I've never seen this behaviour  with any other service so I think this is naemon init related.

**Comment by catharsis** [comment]
I think this might be https://jira.op5.com/browse/MON-8566. If so, it's fixed now. I'm closing for now, feel free to reopen if it reappears.
