### ISSUE TITLE
Inconsistent code/docs for host check_period

### ISSUE THREAD

**Issue by julianbrost** [naemon/naemon-core#84]
The [docs on host objects](http://www.naemon.org/documentation/usersguide/objectdefinitions.html#host_definition) list `check_period` as a required attribute but Naemon starts fine (even without warnings) if it's not set. In this case I guess it works just like if the time period was set to `24x7`.

For services there is a check at [naemon/configuration.c:1505](https://github.com/naemon/naemon-core/blob/afd6912d90650af6d365421cd066f2edf3e9143d/naemon/configuration.c#L1505) but for hosts there is only a check at [naemon/configuration.c:1585](https://github.com/naemon/naemon-core/blob/afd6912d90650af6d365421cd066f2edf3e9143d/naemon/configuration.c#L1585) which only checks whether the timeperiod is valid if any is given.

This behavior should either be changed or documented. There might be similar problems for other attributes but `check_period` was the only one I looked at.

**Comment by catharsis** [comment]
I've opened https://github.com/naemon/naemon.github.io/issues/59 to track this documentation update instead. Thanks for reporting it @julianbrost, and sorry for the late feedback!
