### ISSUE TITLE
help2man not found in make-all in current master

### ISSUE THREAD

**Issue by nook24** [naemon/naemon-core#95]
Hi, not sure if this is the right place to post... I installed the current master right now on Ubuntu 14.04 with./configure;make-all;make install and got this little error:

/bin/bash /root/naemon0.9/naemon.0.9/missing help2man --no-info --section=8 --help-option=-h -n "monitoring core" ./src/naemon/naemon > naemon.8
/root/naemon0.9/naemon.0.9/missing: Line 81: help2man: Command not found.
WARNING: 'help2man' is missing on your system.
         You should only need it if you modified a dependency of a man page.
         You may want to install the GNU Help2man package:
         <http://www.gnu.org/software/help2man/>

May be you can add this to the configure like gperf
Issue fixed by apt install help2man
Best regards,
Daniel

**Comment by ageric** [comment]
It's already in there, but ./configure doesn't say it's looking for it. I'll look into it.

**Comment by catharsis** [comment]
We don't want to halt the build if `help2man` is not present, since it is not required for all use cases. For example, I've normally no need of generating man pages when doing regular patching.

I've submitted a patch for review which generates a warning during `configure` if it's missing, however.
