### ISSUE TITLE
version.sh wasn't updated for 1.0.0

### ISSUE THREAD

**Issue by julianbrost** [naemon/naemon-core#98]
https://github.com/naemon/naemon-core/blob/v1.0.0/version.sh still says version 0.9.1.

This at least affects the Packges for Debian wheezy from labs.consol.de where the Version at "Process Info" in Thruk is reported as 0.9.1-source.

**Comment by sni** [comment]
Thanks, should be fixed with https://github.com/naemon/naemon/commit/4d4b3753b1065ec798225ff5196e8303cbb11c95
