### ISSUE TITLE
Default files

### ISSUE THREAD

**Issue by pelicanmedia** [naemon/naemon-core#99]
Please can you stop the default switch.cfg, printer.cfg and windows.cfg in /etc/naemon/conf.d/ from being created when updating.
These are what cause my "Naemon: ERROR: failed to open socket /var/cache/naemon/live: No such file or directory (/var/cache/naemon/live)" errors after EVERY update.
Please can you make the setup script to check to see if they are there, if not create them. If they are there, leave them alone.
Fair enough on a new install, but not when upgrading to a newer version. Thank you.

**Comment by ageric** [comment]
How are you upgrading? If you're using source, no config should be installed if /etc/naemon/conf.d is a directory at install-time. Have you created a symlink? We could change it so we take symlinks into account as well (and we probably should). I just want to make sure what we're fixing will take care of the problem you're having.

**Comment by pelicanmedia** [comment]
Hi,
I am just using `yum update -y`
I have not created any symlinks. I do not use the switch.cfg, printer.cfg and windows.cfg in /etc/naemon/conf.d/ as I have created my own *.cfg files.

**Comment by pelicanmedia** [comment]
Still not fixed I see.

**Comment by sni** [comment]
The files are installed by "%config(noreplace)" in the naemon.spec file. So if that leads to files being installed, even if the user has removed them before, then this is bug in RPMs and i have no clue how to fix that in our spec file. Suggestions welcome. A dirty workaround could be to not remove the files, but empty them.
Other solution would be to move the sample config files into a seperate package.

**Comment by ageric** [comment]
Hmm... Either we can install the files in the %post section 'if test $1 == 1' (that is, if it's a fresh install) and otherwise not touch them. That means that people who remove naemon and then reinstall it will get the files reinstalled alongside the new install, but that's an explainable problem that we really don't have to solve.

**Comment by sni** [comment]
should be better with https://github.com/naemon/naemon/commit/5711b2bfc5da5676f68d926dcb7a37e53f15d161
